function status=select_opts(status)

status.opts=struct( ...
    'usenoise',1,...
    'useLinQuad',1,...
    'useMinQuad',1,...
    'useLinBpm',1,...
    'useMinBpm',1,...
    'useLaunchfit',1);

if status.opts.usenoise==0
    status.opts.useLinBpm=0;
    status.opts.useMinQuad=0;
    status.opts.useLinBpm=0;
    status.opts.useMinBpm=0;
end
